management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8989
spring:
  application:
    name: turbine-service

logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: error

turbine:
  appConfig: ${TURBINE_APPS:user-service}
  clusterNameExpression: ${TURBINE_CLUSTER_NAME_EXP:'default'}
  aggregator:
    clusterConfig: ${TURBINE_CLUSTERS:default}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8989
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
