package com.huawei.account.cseaccountservice.entity;

public class TAccount {
  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column t_account.ID
   *
   * @mbg.generated
   */
  private String id;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column t_account.USER_ID
   *
   * @mbg.generated
   */
  private String userId;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column t_account.USER_ACCOUNT
   *
   * @mbg.generated
   */
  private String userAccount;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column t_account.USER_PWD
   *
   * @mbg.generated
   */
  private String userPwd;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column t_account.REST_MONEY
   *
   * @mbg.generated
   */
  private Double restMoney;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column t_account.ID
   *
   * @return the value of t_account.ID
   *
   * @mbg.generated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column t_account.ID
   *
   * @param id the value for t_account.ID
   *
   * @mbg.generated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column t_account.USER_ID
   *
   * @return the value of t_account.USER_ID
   *
   * @mbg.generated
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column t_account.USER_ID
   *
   * @param userId the value for t_account.USER_ID
   *
   * @mbg.generated
   */
  public void setUserId(String userId) {
    this.userId = userId == null ? null : userId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column t_account.USER_ACCOUNT
   *
   * @return the value of t_account.USER_ACCOUNT
   *
   * @mbg.generated
   */
  public String getUserAccount() {
    return userAccount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column t_account.USER_ACCOUNT
   *
   * @param userAccount the value for t_account.USER_ACCOUNT
   *
   * @mbg.generated
   */
  public void setUserAccount(String userAccount) {
    this.userAccount = userAccount == null ? null : userAccount.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column t_account.USER_PWD
   *
   * @return the value of t_account.USER_PWD
   *
   * @mbg.generated
   */
  public String getUserPwd() {
    return userPwd;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column t_account.USER_PWD
   *
   * @param userPwd the value for t_account.USER_PWD
   *
   * @mbg.generated
   */
  public void setUserPwd(String userPwd) {
    this.userPwd = userPwd == null ? null : userPwd.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column t_account.REST_MONEY
   *
   * @return the value of t_account.REST_MONEY
   *
   * @mbg.generated
   */
  public Double getRestMoney() {
    return restMoney;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column t_account.REST_MONEY
   *
   * @param restMoney the value for t_account.REST_MONEY
   *
   * @mbg.generated
   */
  public void setRestMoney(Double restMoney) {
    this.restMoney = restMoney;
  }
}