package com.huawei.account.cseaccountservice.entity;

public class TAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.TOTAL_BALANCE
     *
     * @mbg.generated
     */
    private Double totalBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.RESERVED
     *
     * @mbg.generated
     */
    private Boolean reserved;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.ID
     *
     * @return the value of t_account.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.ID
     *
     * @param id the value for t_account.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.TOTAL_BALANCE
     *
     * @return the value of t_account.TOTAL_BALANCE
     *
     * @mbg.generated
     */
    public Double getTotalBalance() {
        return totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.TOTAL_BALANCE
     *
     * @param totalBalance the value for t_account.TOTAL_BALANCE
     *
     * @mbg.generated
     */
    public void setTotalBalance(Double totalBalance) {
        this.totalBalance = totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.RESERVED
     *
     * @return the value of t_account.RESERVED
     *
     * @mbg.generated
     */
    public Boolean getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.RESERVED
     *
     * @param reserved the value for t_account.RESERVED
     *
     * @mbg.generated
     */
    public void setReserved(Boolean reserved) {
        this.reserved = reserved;
    }
}