management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 7979
spring:
  application:
    name: hystrix-dashboard

logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: error

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true
    non-secure-port: 7979
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
