package com.huawei.account.cseaccountservice.mapper;

import com.huawei.account.cseaccountservice.entity.TAccount;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_account",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_account (ID, TOTAL_BALANCE, ",
        "RESERVED)",
        "values (#{id,jdbcType=INTEGER}, #{totalBalance,jdbcType=DECIMAL}, ",
        "#{reserved,jdbcType=BIT})"
    })
    int insert(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, TOTAL_BALANCE, RESERVED",
        "from t_account",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TOTAL_BALANCE", property="totalBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="RESERVED", property="reserved", jdbcType=JdbcType.BIT)
    })
    TAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, TOTAL_BALANCE, RESERVED",
        "from t_account"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TOTAL_BALANCE", property="totalBalance", jdbcType=JdbcType.DECIMAL),
        @Result(column="RESERVED", property="reserved", jdbcType=JdbcType.BIT)
    })
    List<TAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated
     */
    @Update({
        "update t_account",
        "set TOTAL_BALANCE = #{totalBalance,jdbcType=DECIMAL},",
          "RESERVED = #{reserved,jdbcType=BIT}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TAccount record);
}