package com.huawei.account.cseaccountservice.mapper;

import com.huawei.account.cseaccountservice.entity.TAccount;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TAccountMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table t_account
   *
   * @mbg.generated
   */
  @Delete({
      "delete from t_account",
      "where ID = #{id,jdbcType=VARCHAR}"
  })
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table t_account
   *
   * @mbg.generated
   */
  @Insert({
      "insert into t_account (ID, USER_ID, ",
      "USER_ACCOUNT, USER_PWD, ",
      "REST_MONEY)",
      "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
      "#{userAccount,jdbcType=VARCHAR}, #{userPwd,jdbcType=VARCHAR}, ",
      "#{restMoney,jdbcType=DECIMAL})"
  })
  @SelectKey(keyProperty = "id", resultType = String.class, before = true,
      statement = "select replace(uuid(), '-', '') as id from dual")
  int insert(TAccount record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table t_account
   *
   * @mbg.generated
   */
  @Select({
      "select",
      "ID, USER_ID, USER_ACCOUNT, USER_PWD, REST_MONEY",
      "from t_account",
      "where ID = #{id,jdbcType=VARCHAR}"
  })
  @Results({
      @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
      @Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.VARCHAR),
      @Result(column = "USER_ACCOUNT", property = "userAccount", jdbcType = JdbcType.VARCHAR),
      @Result(column = "USER_PWD", property = "userPwd", jdbcType = JdbcType.VARCHAR),
      @Result(column = "REST_MONEY", property = "restMoney", jdbcType = JdbcType.DECIMAL)
  })
  TAccount selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table t_account
   *
   * @mbg.generated
   */
  @Select({
      "select",
      "ID, USER_ID, USER_ACCOUNT, USER_PWD, REST_MONEY",
      "from t_account"
  })
  @Results({
      @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
      @Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.VARCHAR),
      @Result(column = "USER_ACCOUNT", property = "userAccount", jdbcType = JdbcType.VARCHAR),
      @Result(column = "USER_PWD", property = "userPwd", jdbcType = JdbcType.VARCHAR),
      @Result(column = "REST_MONEY", property = "restMoney", jdbcType = JdbcType.DECIMAL)
  })
  List<TAccount> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table t_account
   *
   * @mbg.generated
   */
  @Update({
      "update t_account",
      "set USER_ID = #{userId,jdbcType=VARCHAR},",
      "USER_ACCOUNT = #{userAccount,jdbcType=VARCHAR},",
      "USER_PWD = #{userPwd,jdbcType=VARCHAR},",
      "REST_MONEY = #{restMoney,jdbcType=DECIMAL}",
      "where ID = #{id,jdbcType=VARCHAR}"
  })
  int updateByPrimaryKey(TAccount record);

  @Update({
      "update t_account",
      "set REST_MONEY = #{restMoney,jdbcType=DECIMAL}",
      "where ID = #{id,jdbcType=VARCHAR}"
  })
  int updateMoneyById(@Param("id") String id, @Param("restMoney") Double money);
}