server:
  port: ${CONFIG_SERVER_PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_LAB_ADDR:https://github.com/heyile/springcloud-houseapp-config.git}
          search-paths: ${GIT_LAB_SEARCH_PATH:/}
          username: ${GIT_LAB_ACCOUNT:heyile}
          password: ${GIT_LAB_PWD:102535@Yile}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:false}
  instance:
    prefer-ip-address: true
    ip-address: ${CONFIG_SERVER_IP:127.0.0.1}
    non-secure-port-enabled: ${CONFIG_SERVER_SSL_NON_SECURE_PORT_ENABLED:true}
    non-secure-port: ${REGISTER_PORT:31010}
    secure-port-enabled: ${CONFIG_SERVER_SSL_ENABLED:false}
    secure-port: ${REGISTER_PORT:31010}



